apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/digitalocean/marketplace-kubernetes/master/stacks/knative/assets/manifests/knative-serving.yaml
patches:
  - certmanager-install-patch.yaml
  - certmanager-config-patch.yaml
  - domain-config-patch.yaml
  - network-config-patch.yaml
