# WordPress service type
service:
  type: ClusterIP

# Enable persistence using Persistent Volume Claims
persistence:
  enabled: true
  storageClassName: do-block-storage
  accessModes: ["ReadWriteOnce"]
  size: 5Gi

# Level of auto-updates to allow. Allowed values: major, minor or none.
wordpressAutoUpdateLevel: minor

# Scheme to use to generate WordPress URLs
wordpressScheme: https

# WordPress credentials
wordpressUsername: <WORDPRESS_USER_HERE>
wordpressPassword: <WORDPRESS_PASSSWORD_HERE>

# External Database details
externalDatabase:
  host: <MYSQL_HOST_HERE>
  port: 25060
  user: <MYSQL_DB_USER_HERE>
  password: <MYSQL_DB_PASSWORD_HERE>
  database: <MYSQL_DB_NAME_HERE>

# Disabling MariaDB
mariadb:
  enabled: false

# Enable ingress record generation for WordPress
ingress:
  enabled: true
  certManager: true
  tls: false
  hostname: <YOUR_DOMAIN_HERE>
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  extraTls:
  - hosts:
      - <YOUR_DOMAIN_HERE>
    secretName: wordpress.local-tls
